service/urls.py
from django.urls import path

from service.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskCompleteUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/complete/update/", TaskCompleteUpdateView.as_view(), name="complete-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete")
]

app_name = "service"

todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("service.urls", namespace="service")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

service/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    mark = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["mark", "datetime"]

service/forms.py
from django import forms

from service.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

service/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from service.forms import TaskForm
from service.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 3


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("service:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("service:task-list")


class TaskCompleteUpdateView(generic.UpdateView):
    model = Task
    fields = ["mark"]
    success_url = reverse_lazy("service:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("service:task-list")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("service:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("service:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("service:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        {% block sideber %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>
      <div class="col-sm-9">
        {% block content %}
        {% endblock %}
        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li>
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li>
        <a href="?page={{ page_obj.next_page_number }}" class="page-item">Next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'service:task-list' %}">Home page</a></li>
  <li class="list-group-item"><a href="{% url 'service:tag-list' %}">Tags</a></li>
</ul>

templates/service/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag?</h1>
  <form action="" method="post">
  {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/service/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/service/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a style="float:right" href="{% url 'service:tag-create' %}" class="btn btn-primary">Add</a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th><strong>Name</strong></th>
        <th><strong>Update</strong></th>
        <th><strong>Delete</strong></th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td>
            <a href="{% url 'service:tag-update' pk=tag.id %}" class="btn btn-secondary">Update</a>
          </td>
          <td>
            <a href="{% url 'service:tag-delete' pk=tag.id %}" class="btn btn-secondary">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tags</p>
  {% endif %}
{% endblock %}

templates/service/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task - {{ task.name }}?</h1>
  <form action="" method="post">
  {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/service/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/service/task_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
      TODO List
      <a style="float:right" href="{% url 'service:task-create' %}" class="btn btn-primary">Add task</a>
    </h1>
    {% if task_list %}
      {% for task in task_list %}
        <h3>
          {{ task.content }}
          {% if task.mark %}
            <span style="color:green">Done</span>
            <a style="float:right" href="{% url 'service:complete-update' pk=task.id %}" class="btn btn-secondary">Undo</a>
          {% else %}
            <span style="color:red">Not done</span>
            <a style="float:right" href="{% url 'service:complete-update' pk=task.id %}" class="btn btn-success">Complete</a>
          {% endif %}
        </h3>
        <p>Created:{{ task.datetime }} {% if task.deadline %}Deadline:{{ task.deadline }}{% endif %}</p>
        <p>
          {% for tag in task.tags.all %}
            <span class="text-muted">Tags: {{ tag.name }}</span>
          {% endfor %}
           <a href="{% url 'service:task-update' pk=task.id %}">Update</a>
           <a href="{% url 'service:task-delete' pk=task.id %}">Delete</a>
        </p>
        <hr>
      {% endfor %}
    {% else %}
        <p>There are no task!</p>
    {% endif %}
{% endblock %}